package com.solarvillage.neworderpermitting.process_definition;

import com.solarvillage.neworderpermitting.data_model.NewOrder;

rule "EvaluateCompensation"

	no-loop 
	ruleflow-group "compensation"
	lock-on-active 
    
    when
        //conditions
        $order : NewOrder( (eletricalPermitResult && !structuralPermitResult) || (!eletricalPermitResult && structuralPermitResult) )
    then
        //actions
        modify($order) {setCompensation(true)};
        System.out.println("Rule fired: " + kcontext.getRule().getName() + " - order: " + $order.toString());

end