package com.solarvillage.neworderpermitting.process_definition;

import com.solarvillage.neworderpermitting.data_model.NewOrder;

rule "EvaluateCompensation"

	no-loop 
	ruleflow-group "compensation"
	lock-on-active 
    
    when
        //conditions
        $order : NewOrder((eletricalPermitResult == true && structuralPermitResult == false) || (eletricalPermitResult == false && structuralPermitResult == true))
    then
        //actions
        System.out.println("Starting rule: " + kcontext.getRule().getName());
        modify($order) {setCompensation(true)};
        System.out.println("Rule fired: " + kcontext.getRule().getName());

end

